### ISSUE TITLE
Add data template

### ISSUE THREAD

**Issue by alex-savin** [c727/home-assistant-tiles#13]
# Incomplete issues will be ignored
- [X] I have read README.md
- [X] I have deleted my browser cache after updating tiles

**Description of problem:**
```
There is not possible to use single button to have different state actions based on status.
Ex, to turn on Harmony activity, it uses Activity ID (XXXXXXX), but to turn off it uses Activity ID (-1)
```

**Expected:**
```
Send different value based on sensor status by single button
```

**Tiles version:**
```
lastest
```

**Home Assistant version:**
```
0.63
```
Thanks in advance!

**Comment by c727** [comment]
why don't you add that logic to your script/automation?

**Comment by c727** [comment]
I think you should use [Template Switch](https://home-assistant.io/components/switch.template/) for this
