### ISSUE TITLE
Where have you gone eddi89 on Home Assistant?

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#14]
A lot of what sounded like useful Tile posts from yourself have disappeared on the thread that you started - any idea what's happening?

https://community.home-assistant.io/t/custom-ui-tiles/29513/181

**Comment by c727** [comment]
I decided to stop posting in the forum.
If you want to stay updated start this repo or use the [update info](https://github.com/c727/home-assistant-tiles#update-info)

**Comment by jarrah31** [comment]
fair enough - thanks for keeping this project going as it's very useful!
