### ISSUE TITLE
have empty space between groups in side-panel?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#16]
HI,

would it be possible to have an empty space between 2 sets of buttons on the side-panel Tiles?

like showing 2 groups n a dedicated card in the regular setup?
thx,
Marius

**Comment by c727** [comment]
Yes but I won't add other dashboard-like features

**Comment by hvbhome** [comment]
not really sure i understand...

yes, as it is already possible (please let me now how)
or yes, that could be done, but it is not going to ;-)

**Comment by c727** [comment]
I mean that I can update the panel code today but I will only add this and won't add support for other elements like showing a clock or a cam stream for example - then you should use a real dashboard like HADashboard

**Comment by hvbhome** [comment]
ok cool, thanks if you would ! Very nice indeed
totally appreciate your position.

Looking forward to that.
Cheers,
Marius

**Comment by c727** [comment]
check the new panel. I hope that is what you expected :)

![panel_multi](https://user-images.githubusercontent.com/11984118/37169610-a8821a28-2308-11e8-9164-ef0f39648421.png)

**Comment by hvbhome** [comment]
Magic! Wonderful. Will implement immediately ;-)
Thx
