### ISSUE TITLE
(App HomeAssistant and )Tiles Panel: how to get back?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#17]
HI,

When clicking the side-panel Tiles in the iOS app HomeAssistant no option is available to get back into the regular HA frontend?
No swiping left or right is possible and a reload won't do it either.
Only kill the app and restart will get the user back into HomeAssistant regular frontend.

Some kind of menu option would be very much appreciated.

btw, the same goes for the panel view in a regular webbrowser (tried safari and chrome on Mac) when the left menu is swiped out left clicking the < button: no option to slide back....

![schermafbeelding 2018-03-08 om 23 17 56](https://user-images.githubusercontent.com/33354141/37179758-022354b6-2327-11e8-883a-0c545b3b53c2.jpg)

**Comment by c727** [comment]
added
