### ISSUE TITLE
need group name?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#21]
would it be possible to leave out the group name of the main Tile, and just show the tiles?
I havent tried to set the text color to the same color as the background, which would make the name invisible, but it would be even better if the name would be optional?

If the above wouldn't be possible, could we, in a grid of lets say 3 x 3, have the main group name in column1 row 1, and a 'main' button on column 3 row 1?

In my example here, have the red/green Power button on the right on the same row as title Lights:

![schermafbeelding 2018-03-10 om 12 44 56](https://user-images.githubusercontent.com/33354141/37241898-f491b082-2460-11e8-8712-8b252329b958.jpg)

![schermafbeelding 2018-03-10 om 12 46 48](https://user-images.githubusercontent.com/33354141/37241904-24e8d468-2461-11e8-99fb-509647d23f7f.jpg)

Would be way cool for the visual impact of a set of tiles.

Cheers,
Marius

**Comment by c727** [comment]
Is this with the panel? The header is optional there...

**Comment by hvbhome** [comment]
No, this is a regular Tiles setup question

**Comment by c727** [comment]
so set the group name to `" "`

**Comment by hvbhome** [comment]
Sorry to re-ask, but that would still take a row wouldn’t it ?

No (future) option for either showing both group name and Master button on the same row , or just take out the row for the group name.?
Seems the tiles side panel does offer this by specifying the grid position of the group name .

Cheers
Marius

**Comment by c727** [comment]
If wont remove the grouper title as it's part of a parent element, you will have to wait until custom UIs are allowed for full cards

if you want a "name" in the first row change the button color to the same color as your background or something like this.
