### ISSUE TITLE
tiles need a lock....

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#24]
HI,

Tiles setup is quickly getting the favorite way of controlling the HomeAssistant setup in this household....So much so, it is becoming dangerous ;-)

It is very easy to click the tiles, and have an immediate response to possible unwanted effect, resulting in the wrong switch switched or profile selected or whatever.

Would it be conceivable to add a confirmable control like on custom-ui https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#confirmable-controls in the customize settings?
Hope for a yes of course, would make the tiles even more family-friendly...

Cheers,
Marius

**Comment by c727** [comment]
you can use `more_info` if you need 2 factor, I wont add a lock

**Comment by hvbhome** [comment]
nice, more_info can also be used on a switch? 
what should we use after the `more_info: ` to have the switch pop-up and be clickable?

**Comment by c727** [comment]
An entity_id, yes all can use it
