### ISSUE TITLE
have buttons use background theme-color

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#29]
Hi,

We can either use the default button color by not stating any color or set a color using `color:` 

When using (transparent) images on the tiles, both cases are somewhat imperfect if one is using theming for the Frontend. Especially so when changing themes eg. during day and night time. It sets the buttons apart from the interface either way.

It appears to be possible to have the buttons take the color of the card background the current theme is using, thus enabling automatic changing along with the theme change. And making the buttons appear to float in the card.

Ive tested this:   ` color: "var(--paper-card-background-color)"` 

and it seems promising! Thanks for this beautiful custom card!

![schermafbeelding 2018-03-15 om 18 03 00](https://user-images.githubusercontent.com/33354141/37478661-22ef709a-287b-11e8-9b00-e9673a761b8d.jpg)

![schermafbeelding 2018-03-15 om 18 04 52](https://user-images.githubusercontent.com/33354141/37478777-6f0372c4-287b-11e8-9056-905bd6aae076.jpg)

compared to a set color:

![schermafbeelding 2018-03-15 om 18 03 36](https://user-images.githubusercontent.com/33354141/37478691-3a6f56d6-287b-11e8-85b7-a7dfaca0072a.jpg)

![schermafbeelding 2018-03-15 om 18 05 01](https://user-images.githubusercontent.com/33354141/37478786-756dfa9e-287b-11e8-863c-7bf591a00161.jpg)

Just liked to let you know. NO issue!

Cheers,
Marius

**Comment by c727** [comment]
Yep, that's the best way if you use themes else you can also use rgba or hsla colors :)

**Comment by c727** [comment]
Btw, if you don't set a group header/name you can create your "show header in first row" with this

**Comment by hvbhome** [comment]
O that would be wonderful. Is it in the docs? Or, how could I do that?

**Comment by c727** [comment]
label_template changes the text, style_template can change the color

**Comment by hvbhome** [comment]
Ok thanks, I've been trying to combine the two into this but it won't color the text:

style_template: "if (entities['group.all_lights_only'].state === 'on') return 'red'; else return 'green'; return 'min-height: 25px;'"

this label_template works fine, 

```
label_template: "if (entities['group.all_lights_only'].state === 'on') 
                                 return 'Lights on'; else return 'All off';"
```
so im positive that is correct, also in the style_template. Am i missing a : or "" somewhere?

**Comment by c727** [comment]
```
style_template: "if (entities['group.all_lights_only'].state === 'on') return 'color: red; min-height: 25px;'; else return 'color: green; min-height: 25px';"
```

**Comment by hvbhome** [comment]
thanks!
Magic again...

![schermafbeelding 2018-03-16 om 18 07 24](https://user-images.githubusercontent.com/33354141/37534389-02ce946a-2945-11e8-8b7d-4a8bb74170ad.jpg)
![schermafbeelding 2018-03-16 om 18 07 34](https://user-images.githubusercontent.com/33354141/37534390-02ec843e-2945-11e8-9b05-663ef126bec7.jpg)
just for the fun of it...
