### ISSUE TITLE
Support for Panel_custom

### ISSUE THREAD

**Issue by bhaap** [c727/home-assistant-tiles#3]
would be awesome to have this in a custom panel for the use on like a wall-mounted tablet.

https://home-assistant.io/components/panel_custom/

This is to get rid of the menu ontop showing the views.

**Comment by c727** [comment]
What's the problem using it in a panel? I can upload an older example panel in about 1 hour...

**Comment by bhaap** [comment]
I didnt know it supported it because there was no example about it. Sorry im not a dev so didnt know.

**Comment by c727** [comment]
I uploaded a panel
