### ISSUE TITLE
input_select as button/tile?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#35]
Hi,

How could we use an input select on a tile?
woud be really nice to use existing selects by 

```
entity: input_select.selection
image: selection.png
select_option: selection1

```
could this be?
theres nothing in the documentation?

If not yet possible, would you please consider adding it, it would be real convenient.

Cheers,
Marius

**Comment by c727** [comment]
I won't add it, tiles is only for buttons

**Comment by hvbhome** [comment]
sorry, maybe i've misexpressed myself. I fully understand that. Didnt mean to ask for an input_select in the frontend. On the contrary , meant to represent that by presenting buttons for each option of the input_select.
if an input_select has 4 options, i would have wanted to create four buttons for that.
