### ISSUE TITLE
error related to update notification

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#36]
all of a sudden i get many of these errors:
```

Error parsing value: 'value_json' is undefined (value: Loop detected on cache-ams4137-AMS: TuFMEtJVICCO9h0Zpde/N9L9b7tugV9xeSSEt9M0!AMS!cache-ams4137-AMS
, template: {{ value_json.homeassistant }})
```

which then turn into a regular update notification if the new version of Tiles (which i already have installed...)

did you by any chance change something in the update sensor?

cheers,
Marius

**Comment by c727** [comment]
no -.-"
