### ISSUE TITLE
Detect unavailable state of an entity and change tile colour?

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#39]
## Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles
- [x] I run Home Assistant 0.66 or later
- [x] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
Sometimes my lights show a state of 'unavailable' and tiles interprets this as being 'on'. Is there a way to specify a tile colour depending on the state name please? e.g. something along the line of:
`"if (state == 'unavailable'){return 'red'}"`
**Tiles version shown in HA:**
```
Version: 20180320
```

**Entity:**
```
- entity: light.bedside3
  label: Bed3
  icon: mdi:lamp
  column: 2
  row: 10
```

**Home Assistant version:**
```
65.5
```

**Screenshot:**
<img width="797" alt="screen shot 2018-03-30 at 10 56 18" src="https://user-images.githubusercontent.com/3072303/38134206-e965a3e0-3409-11e8-9ae7-9edd5bee0c2b.png">
<img width="470" alt="screen shot 2018-03-30 at 11 04 18" src="https://user-images.githubusercontent.com/3072303/38134301-4a303672-340a-11e8-8027-e3b9efc77a27.png">

**Comment by c727** [comment]
What would be the expected on-click behavior for this case, show the more info dialog?

**Comment by jarrah31** [comment]
I was thinking along the lines of it just being status indicator where the red tile colour would just mean an issue for me to investigate, leaving the on-click behaviour for the usual light on/off.

**Comment by c727** [comment]
should be fixed in the new release
