### ISSUE TITLE
text-decoration: line-through not working?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#43]
as title.

```
        entities:
          - entity: switch.sw_audio_auditorium_template
            label_sec: Auditorium
            icon_template: "if (state === 'on') return 'mdi:music';
                            else return 'mdi:music-off';"
            style_template: "if (state !== 'on') return 'text-decoration: line-through';"

          - entity: switch.sw_tv_auditorium_template
            label_sec: Auditorium
            icon_template: "if (state === 'on') return 'mdi:television';
                            else return 'mdi:television-off';"
            style_template: "if (state !== 'on') return 'text-decoration: line-through';"
```

![schermafbeelding 2018-04-13 om 07 43 11](https://user-images.githubusercontent.com/33354141/38718658-6b67fcaa-3eee-11e8-920a-b689715d404a.jpg)

Could this style_template be off somehow? copied straight from your configuration file. 
state is read fine, as shown by the icon, and tile itself does work as expected.

btw this is the set of tiles showing the odd behavior when a persistent message is being dismissed, as posted in the [other issue](https://github.com/c727/home-assistant-tiles/issues/28). (which didn't have this style_template yet)

**Comment by c727** [comment]
it's working. I should blacklist safari on next release

**Comment by hvbhome** [comment]
Ok I can see that might be a detail...
otoh,  the iOS app is showing the same ...
