### ISSUE TITLE
Feature request: Show / Hide based on a state

### ISSUE THREAD

**Issue by scottsweb** [c727/home-assistant-tiles#45]
I am using your project to create a remote control interface that looks like this:

![screenshot-20180427211330-1007x1247](https://user-images.githubusercontent.com/411945/39383096-e76eaf0c-4a5f-11e8-9a0d-8e2c7945d77b.png)

I am thinking it would be great to switch out the purple buttons based on the current input of the TV. I would like to propose a new entity field `visible` that can be either true or false based on the state of other inputs, selects etc.

**Comment by scottsweb** [comment]
Thanks for the tip, I will give this a try.

**Comment by c727** [comment]
So use 1 script instead of 3 scenes
