### ISSUE TITLE
Error in latest frontend build 0.70.0b0

### ISSUE THREAD

**Issue by mynameisdaniel32** [c727/home-assistant-tiles#48]
**Description of problem:**
Since the latest frontend update, I've been unable to use tiles in Home Assistant. I keep pretty regularly up-to-date with dev and the previous frontend version was working, so I suspect [this](https://github.com/home-assistant/home-assistant-polymer/commit/e1c9f3deea65a869be662482fd684195ccf92d65) change has caused this issue.

In my logs I get
```
2018-05-18 22:09:08 ERROR (MainThread) [frontend.js.latest.201805180] https://REDACTED.duckdns.org/local/custom_ui/state-card-tiles.html:90:50 Uncaught TypeError: Cannot read property 'EventsMixin' of undefined
```
I did have a bit of a play trying to swap out EventsMixin and NavigateMixin but didn't have any luck.

**Expected:**
Tiles to display

**Tiles version shown in Home Assistant developer info:**
```
20180420.2
```

**Affected browser:**
```
All (Chrome, Firefox, iOS app tried)
```

**Home Assistant version:**
```
0.70.0.dev0 (2018-05-18)
```

**Home Assistant `frontend:` config:**
```yaml
Unchanged
```

**Home Assistant `customize:` config:**
```yaml
Unchanged
```

**Error log from browser dev console - NOT from HA:**
```
state-card-tiles.html:90 Uncaught TypeError: Cannot read property 'EventsMixin' of undefined
    at state-card-tiles.html:90
```

**Screenshot:**
<<here>>
![image](https://user-images.githubusercontent.com/24840952/40235243-d840a910-5ae8-11e8-82f6-b29515039d2f.png)

**Comment by mynameisdaniel32** [comment]
As a workaround for this, force loading the es5 version works okay (i.e add ?es5 to the end of the URL).

**Comment by balloob** [comment]
It looks like you are running an old update of this custom panel. There is no reference of EventsMixin in the source https://github.com/c727/home-assistant-tiles/blob/master/panels/tiles.html

**Comment by c727** [comment]
fixed in latest release
